version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://instatus:instatus@db:5432/activity"
    depends_on:
      - db
    entrypoint: ["sh", "-c", "./wait-for-it.sh db:5432 -- npx prisma migrate deploy && npm start"]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: instatus
      POSTGRES_PASSWORD: instatus
      POSTGRES_DB: activity
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
